# Generated by Django 5.1.2 on 2024-11-08 20:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('waste_dump', 'Свалка мусора'), ('recycling_point', 'Пункт приёма мусора')], max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('in_progress', 'Очистка в процессе'), ('cleaned', 'Очищено')], default='active', max_length=15, verbose_name='Статус')),
                ('players_ids', models.JSONField(blank=True, default=list, verbose_name='ID участников')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер свалки')),
                ('authors', models.ManyToManyField(related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
            ],
        ),
    ]
