# Generated by Django 5.1.2 on 2024-11-09 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='location',
            name='size',
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/', verbose_name='Изображение локации'),
        ),
        migrations.AlterField(
            model_name='location',
            name='players_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='ID игроков'),
        ),
    ]
