# Generated by Django 5.1.2 on 2024-11-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_map', '0002_remove_location_address_remove_location_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
