# Generated by Django 5.1.2 on 2024-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_map', '0004_location_address_location_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPhotoView',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('photo_id', models.CharField(blank=True, max_length=250, null=True)),
                ('bot_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('bot_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('bot_comments', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'location_photo_view',
                'managed': False,
            },
        ),
    ]
