# Generated by Django 5.1.2 on 2025-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_barterrequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterrequest',
            name='barter_type',
            field=models.CharField(choices=[('search', 'Поиск'), ('exchange', 'Обмен'), ('gift', 'Дарение')], default='exchange', max_length=10, verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='compensatory_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма компенсации в баллах'),
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценочная стоимость в баллах'),
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('pending', 'Ожидает подтверждения'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='barterrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='barterrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='barterrequest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок заявки'),
        ),
    ]
