# Generated by Django 5.1.2 on 2025-02-08 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_barterrequest_barter_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterrequest',
            name='barter_type',
            field=models.CharField(choices=[('exchange', 'Обмен'), ('gift', 'Дарение')], default='exchange', max_length=10, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='barterrequest',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='barter_requests', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BarterDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Компенсация в баллах')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('active', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=10, verbose_name='Статус сделки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_deals', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('item_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='barter.barterrequest', verbose_name='Товар инициатора')),
                ('item_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offer', to='barter.barterrequest', verbose_name='Товар партнера (если обмен)')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participated_deals', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
