# Generated by Django 5.1.2 on 2025-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0004_alter_barterrequest_barter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barter_images/'),
        ),
    ]
