# Generated by Django 5.1.2 on 2025-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0005_barterrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterrequest',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='Зарезервирован в сделке'),
        ),
    ]
