# Generated by Django 5.1.2 on 2025-02-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0006_barterrequest_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterdeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('started', 'Начата'), ('active', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус сделки'),
        ),
    ]
