# Generated by Django 5.1.2 on 2025-02-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0007_alter_barterdeal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
