# Generated by Django 5.1.2 on 2025-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0008_userbalance_reserved_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterdeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('started', 'Начата'), ('active', 'В работе'), ('in_transit', 'В дороге'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус сделки'),
        ),
    ]
