# Generated by Django 5.1.2 on 2025-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0009_alter_barterdeal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterdeal',
            name='initiator_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barterdeal',
            name='partner_received',
            field=models.BooleanField(default=False),
        ),
    ]
