# Generated by Django 5.1.2 on 2025-01-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_map', '0006_photo_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
