# Generated by Django 5.1.2 on 2024-11-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
