# Generated by Django 5.1.2 on 2025-02-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_is_hot_news_likes_count_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_hot', '-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
